/**
 * SSOT: 저장소 루트 `contracts/errorCodes.ts`와 동일 스냅샷.
 * 서버 `rootDir` 제약으로 여기서 동일 내용을 유지한다.
 */
export const ErrorCodes = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  OAUTH_PROVIDER_ERROR: 'OAUTH_PROVIDER_ERROR',
  OAUTH_CANCELLED: 'OAUTH_CANCELLED',
  ACCOUNT_CONFLICT: 'ACCOUNT_CONFLICT',
  SOCIAL_STATE_INVALID: 'SOCIAL_STATE_INVALID',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  MEAL_SET_ITEM_UNAVAILABLE: 'MEAL_SET_ITEM_UNAVAILABLE',
  OCR_RATE_LIMIT: 'OCR_RATE_LIMIT',
  OCR_PROVIDER_UNAVAILABLE: 'OCR_PROVIDER_UNAVAILABLE',
  OCR_PARSE_FAILED: 'OCR_PARSE_FAILED',
  OCR_FREE_QUOTA_EXCEEDED: 'OCR_FREE_QUOTA_EXCEEDED',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  BILLING_NOT_AVAILABLE: 'BILLING_NOT_AVAILABLE',
  STATS_STALE_DATA: 'STATS_STALE_DATA',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
