export const DEMO_COPY = {
  brand: 'nouryLog AI',
  heroTitle: 'RAG 기반 개인화 영양 AI',
  heroSubtitle:
    '내 식단 DB·pgvector·의도 분류로 답합니다. 단순 챗봇이 아니라, 근거 식단 기록이 붙는 개인화 코치입니다.',
  heroNote: '실제 기록·OCR·구독은 모바일 앱에서 이용합니다. 이 웹은 AI 기능 미리보기용입니다.',
  ctaDemo: '데모 계정으로 바로 체험',
  ctaDemoLoading: '데모 로그인 중…',
  ctaNoCredentials: '데모 계정 env가 없습니다 (VITE_DEMO_EMAIL / VITE_DEMO_PASSWORD)',
  snsDivider: '또는 SNS로 로그인',
  ctaKakao: '카카오로 로그인',
  ctaNaver: '네이버로 로그인',
  googleEnvHint: 'Google: VITE_GOOGLE_CLIENT_ID 설정 시 버튼이 표시됩니다.',
  kakaoEnvHint: 'Kakao: VITE_KAKAO_JAVASCRIPT_KEY를 설정하세요.',
  naverEnvHint: 'Naver: VITE_NAVER_CLIENT_ID, VITE_NAVER_REDIRECT_URI를 설정하세요.',
  demoModeBanner: '시드 데이터 시연 중입니다. 본인 기록을 보려면 로그아웃 후 SNS로 로그인하세요.',
  featureWeekly: '주간 AI 식단 리포트',
  featureWeeklyDesc: '이번 주 섭취·패턴·다음 주 목표',
  featureMonthly: '월간 영양 패턴 분석',
  featureMonthlyDesc: '한 달 습관·추세·다음 달 목표',
  featureCoach: 'AI 코치 챗봇',
  featureCoachDesc: '질문 → intent 분기 → 근거 citation',
  ragBullets: [
    'stats_query — 기간 집계 + 내 Meal DB',
    'semantic_meal — 벡터 검색으로 비슷한 식사',
    'knowledge_query — 영양 지식 문서 RAG',
  ],
  readmeHint: '자동 로그인',
  emptyWeekTitle: '이번 주 식단 기록이 없어요',
  emptyWeekHint: '데모 DB에 시드 데이터가 있는지 확인해 주세요.',
  unknownIntentNote: '식단·영양·내 기록과 관련된 질문만 답할 수 있어요. 아래 예시를 참고해 주세요.',
  envSetupHint:
    'apps/user-web/.env.local에 VITE_DEMO_EMAIL, VITE_DEMO_PASSWORD (또는 VITE_DEV_*)를 설정하세요.',
} as const;
