/**
 * 계약 오류 코드 스냅샷 (Common-C2).
 * SSOT 문서: docs/requirements/feature-diet-management-api-contract-v1.md §7
 * HTTP 매핑 힌트: contracts/error-catalog.json
 */
export const ErrorCodes = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  OCR_RATE_LIMIT: 'OCR_RATE_LIMIT',
  OCR_PROVIDER_UNAVAILABLE: 'OCR_PROVIDER_UNAVAILABLE',
  OCR_PARSE_FAILED: 'OCR_PARSE_FAILED',
  OCR_FREE_QUOTA_EXCEEDED: 'OCR_FREE_QUOTA_EXCEEDED',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  BILLING_NOT_AVAILABLE: 'BILLING_NOT_AVAILABLE',
  STATS_STALE_DATA: 'STATS_STALE_DATA',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
