export const AI_COPY = {
  screenTitle: 'AI 영양 코치',
  screenSubtitle: '주간·오늘 요약과 자연어 질문',
  homeCardTitle: 'AI 코치 요약',
  homeCardOpen: '코치 열기',
  homeCardLoadError: '코치 요약을 불러오지 못했어요.',
  homeCardRetry: '다시 시도',
  anchorLabel: '기준일 (KST)',
  anchorCalendarOpen: '기준일 선택',
  staleBanner: '데이터가 갱신 중일 수 있어요.',
  summaryLoadError: '코치 정보를 불러오지 못했어요.',
  retry: '다시 시도',
  todaySection: (label: string) => `오늘 (${label})`,
  weekAvgSection: '이번 주 일평균',
  weekMeta: (days: number, meals: number) => `기록 ${days}일 · 식사 ${meals}건`,
  proteinShortChip: (n: number) => `단백질 부족 ${n}일`,
  proteinOkChip: '단백질 목표 양호',
  calorieShortChip: (n: number) => `칼로리 미달 ${n}일`,
  calorie: '칼로리',
  protein: '단백질',
  carb: '탄수화물',
  fat: '지방',
  kcalUnit: 'kcal',
  goalMet: '달성',
  goalMiss: '미달',
  goalLine: (goal: number, met: boolean, unit: string) =>
    `목표 ${goal}${unit} · ${met ? '달성' : '미달'}`,
  weekGoalLine: (proteinMet: boolean, proteinGap: number, calorieMet: boolean) =>
    `주간 목표 대비: 단백질 ${proteinMet ? '달성' : `갭 ${proteinGap}g`}, 칼로리 ${calorieMet ? '달성' : '미달'}`,
  insightTitle: 'AI 제안',
  insightTemplateNote: '규칙 기준 제안 (LLM 미사용)',
  macroTitle: '영양소 비율 (주간)',
  evidenceTitle: '근거 기록',
  frequentTitle: '자주 먹은 음식',
  frequentCount: (name: string, count: number) => `${name} (${count}회)`,
  emptyWeekHint: '기록 탭에서 식단을 추가한 뒤 다시 확인해 주세요.',
  emptyWeekCta: '식단 기록하기',
  askSectionTitle: '질문하기',
  askPlaceholder: '식단·영양에 대해 물어보세요',
  askSubmit: '질문하기',
  askSubmitting: '분석 중…',
  askError: '질문을 처리하지 못했어요.',
  expectedIntent: (label: string) => `예상 분석: ${label}`,
  intentStats: '기간 집계',
  intentSemantic: '식단 검색',
  intentKnowledge: '영양 지식',
  answerIntent: (label: string) => `분석 유형: ${label}`,
  answerNoLlm: '검색·집계 기준으로 답변했어요 (LLM 미사용).',
  answerNoMeals: '해당 기간 식단 기록이 없습니다. 기록을 추가해 주세요.',
  citationsTitle: '근거',
  rateLimitToast: '질문이 너무 많아요. 잠시 후 다시 시도해 주세요.',
  weeklyReportTitle: '이번 주 AI 식단 리포트',
  weeklyReportDesc:
    '최근 7일 기록을 바탕으로 식사 패턴·부족한 영양·다음 주 목표를 제안합니다.',
  weeklyKeySummary: '이번 주 핵심 요약',
  weeklyMetricBreakfastSkip: (n: number) => `아침 결식 ${n}일`,
  weeklyMetricProteinShort: (n: number) => `단백질 부족 끼니 ${n}회`,
  weeklyMetricOutside: (n: number) => `외식·배달 ${n}회`,
  weeklyMetricVeg: (n: number) => `채소 포함 ${n}회`,
  weeklyAiComment: 'AI 코멘트',
  weeklyEvidenceTitle: '근거 기록',
  weeklyGoalsTitle: '다음 주 추천 목표',
  weeklyTemplateNote: '템플릿 요약 (LLM 미사용)',
  weeklyLoadError: '주간 리포트를 불러오지 못했어요.',
  monthlyPatternTitle: '이번 달 영양 패턴',
  monthlyPatternDesc:
    '한 달 기록의 반복 습관·추세를 분석하고 다음 달 목표를 제안합니다.',
  monthlyRecurringTitle: '반복 패턴',
  monthlyTrendTitle: '개선 추세',
  monthlyAiComment: 'AI 분석',
  monthlyGoalsTitle: '다음 달 목표',
  monthlyLoadError: '월간 패턴 분석을 불러오지 못했어요.',
  portfolioWeeklyOneLiner:
    '최근 7일 식단 기록 기반 식사 패턴·영양 부족·다음 주 개선 목표 AI 리포트',
  portfolioMonthlyOneLiner:
    '한 달 식단 집계 기반 결식·반복 섭취·추세 분석 및 다음 달 목표 AI 분석',
  loading: '불러오는 중…',
} as const;

export function aiIntentLabel(intent: string): string | null {
  if (intent === 'stats_query') return AI_COPY.intentStats;
  if (intent === 'semantic_meal') return AI_COPY.intentSemantic;
  if (intent === 'knowledge_query') return AI_COPY.intentKnowledge;
  return null;
}
