export const BILLING_COPY = {
  title: '구독',
  freeBadge: '무료 플랜',
  premiumBadge: '프리미엄',
  freeBenefit1: 'OCR 무료 5회(누적)',
  freeBenefit2: '하단 광고 노출',
  premiumBenefit1: 'OCR 추가 사용',
  premiumBenefit2: '하단 광고 제거',
  premiumPrice: '월 4,900원',
  skuLabel: 'premium_monthly',
  subscribeCta: '프리미엄 구독하기',
  restoreCta: '구매 복구',
  subscribeSuccess: '구독이 활성화되었어요. OCR·광고 설정이 갱신됩니다.',
  restoreSuccess: '구매 복구를 요청했어요. 잠시 후 상태를 확인해 주세요.',
  loadError: '구독 정보를 불러오지 못했어요.',
  actionError: '처리하지 못했어요. 잠시 후 다시 시도해 주세요.',
  paywallTitle: '무료 OCR를 모두 사용했어요',
  paywallBody: '프리미엄 월 구독으로 OCR 추가 사용과 광고 제거를 이용할 수 있어요.',
  paywallCta: '프리미엄 구독하기',
  paywallDismiss: '나중에',
} as const;
