export const BILLING_COPY = {
  title: '플랜',
  freeBadge: '무료 플랜',
  premiumBadge: '프리미엄',
  freeBenefit1: '영양표 사진 분석 (매월 무료 제공)',
  freeBenefit2: '하단 광고 노출',
  premiumBenefit1: '사진 분석 추가 사용',
  premiumBenefit2: '하단 광고 제거',
  premiumPrice: '월 4,900원',
  skuLabel: 'premium_monthly',
  premiumComingSoon: '프리미엄 구독은 추후 제공 예정이에요.',
  subscribeCta: '프리미엄 구독하기',
  restoreCta: '구매 복구',
  subscribeSuccess: '구독이 활성화되었어요. 사진 분석·광고 설정이 갱신됩니다.',
  restoreSuccess: '구매 복구를 요청했어요. 잠시 후 상태를 확인해 주세요.',
  loadError: '플랜 정보를 불러오지 못했어요.',
  actionError: '처리하지 못했어요. 잠시 후 다시 시도해 주세요.',
  paywallTitle: '이번 달 무료 사진 분석을 모두 사용했어요',
  paywallBody: '다음 달에 무료 횟수가 다시 채워져요. 수동 입력으로 기록을 이어갈 수 있어요.',
  paywallBodyBilling: '프리미엄 월 구독으로 사진 분석 추가 사용과 광고 제거를 이용할 수 있어요.',
  paywallCta: '프리미엄 구독하기',
  paywallDismiss: '확인',
  photoAnalysisUsage: (used: number, limit: number) => `이번 달 사진 분석 ${used}/${limit}회`,
} as const;
