export const INSIGHT_COPY = {
  screenTitle: '식단 인사이트',
  screenSubtitle: '최근 7일·오늘 기록 요약과 패턴',
  homeCardTitle: '식단 인사이트',
  homeCardOpen: '자세히 보기',
  homeCardLoadError: '인사이트를 불러오지 못했어요.',
  homeCardRetry: '다시 시도',
  anchorLabel: '기준일 (KST)',
  anchorCalendarOpen: '기준일 선택',
  staleBanner: '데이터가 갱신 중일 수 있어요.',
  summaryLoadError: '인사이트를 불러오지 못했어요.',
  retry: '다시 시도',
  todaySection: (label: string) => `오늘 (${label})`,
  weekAvgSection: '최근 7일 일평균',
  weekMeta: (days: number, meals: number) => `기록 ${days}일 · 식사 ${meals}건`,
  proteinShortChip: (n: number) => `단백질 부족 ${n}일`,
  proteinOkChip: '단백질 목표 양호',
  calorieShortChip: (n: number) => `칼로리 미달 ${n}일`,
  calorie: '칼로리',
  protein: '단백질',
  carb: '탄수화물',
  fat: '지방',
  kcalUnit: 'kcal',
  goalMet: '달성',
  goalMiss: '미달',
  goalLine: (goal: number, met: boolean, unit: string) =>
    `목표 ${goal}${unit} · ${met ? '달성' : '미달'}`,
  weekGoalLine: (proteinMet: boolean, proteinGap: number, calorieMet: boolean) =>
    `최근 7일 목표 대비: 단백질 ${proteinMet ? '달성' : `갭 ${proteinGap}g`}, 칼로리 ${calorieMet ? '달성' : '미달'}`,
  insightTitle: '최근 7일 제안',
  macroTitle: '영양소 비율 (최근 7일)',
  evidenceTitle: '근거 기록',
  frequentTitle: '자주 먹은 음식',
  frequentCount: (name: string, count: number) => `${name} (${count}회)`,
  emptyWeekHint: '기록 탭에서 식단을 추가한 뒤 다시 확인해 주세요.',
  emptyWeekCta: '식단 기록하기',
  noMealsInPeriod: '해당 기간 식단 기록이 없습니다. 기록을 추가해 주세요.',
  weeklyReportTitle: '최근 7일 식단 리포트',
  weeklyReportDesc: '최근 7일 기록을 바탕으로 식사 패턴·부족한 영양·다음 목표를 안내합니다.',
  weeklyKeySummary: '최근 7일 핵심 요약',
  weeklyMetricBreakfastSkip: (n: number) => `아침 결식 ${n}일`,
  weeklyMetricProteinShort: (n: number) => `단백질 부족 끼니 ${n}회`,
  weeklyComment: '한 줄 요약',
  weeklyEvidenceTitle: '근거 기록',
  weeklyGoalsTitle: '다음 7일 추천 목표',
  weeklyLoadError: '주간 리포트를 불러오지 못했어요.',
  monthlyPatternTitle: '이번 달 영양 패턴',
  monthlyPatternDesc: '한 달 기록의 반복 습관·추세를 분석하고 다음 달 목표를 제안합니다.',
  monthlyRecurringTitle: '반복 패턴',
  monthlyTrendTitle: '개선 추세',
  monthlyComment: '한 줄 요약',
  monthlyGoalsTitle: '다음 달 목표',
  monthlyLoadError: '월간 패턴을 불러오지 못했어요.',
  loading: '불러오는 중…',
} as const;
