export const LOG_COPY = {
  title: '기록',
  subtitle: '영양표 사진 또는 아래에서 음식을 골라 기록해요.',
  photoGuideTitle: '어떤 사진이 좋나요?',
  photoGuideBody:
    '포장지·영양성분표에서 칼로리, 단백질, 탄수화물, 지방이 보이게 촬영해 주세요. 빛 반사·흔들림이 적을수록 정확해요.',
  photoGuideAlbum: '이미 찍어 둔 라벨 사진을 앨범에서 선택해도 됩니다.',
  ocrCamera: '영양표 촬영',
  ocrAlbum: '앨범에서 선택',
  photoAnalysisChip: (used: number, limit: number) => `사진 분석 이번 달 ${used}/${limit}회`,
  ocrLowConfidence: '인식 신뢰도가 낮아요. 영양 값을 꼭 확인해 주세요.',
  ocrBannerRemaining: '이번 달 무료 사진 분석이 1회 남았어요.',
  ocrBannerExhausted: '이번 달 무료 사진 분석을 모두 사용했어요.',
  ocrPickCanceled: '이미지 선택이 취소되었습니다.',
  ocrCameraCanceled: '촬영이 취소되었습니다.',
  ocrCameraFailed: '카메라를 열지 못했어요. 권한을 확인하거나 다시 시도해 주세요.',
  ocrAlbumFailed: '앨범을 열지 못했어요. 권한을 확인하거나 다시 시도해 주세요.',
  ocrCameraPermissionDenied: '카메라 접근 권한이 필요합니다.',
  ocrCameraPermissionSettings: '카메라 권한이 꺼져 있어요. 설정에서 허용해 주세요.',
  ocrAlbumPermissionDenied: '갤러리 접근 권한이 필요합니다.',
  ocrAlbumPermissionSettings: '사진 접근 권한이 꺼져 있어요. 설정에서 허용해 주세요.',
  ocrImageLoadFailed: '이미지를 불러오지 못했어요. 다른 사진을 선택해 주세요.',
  ocrImageTooLarge:
    '이미지가 너무 커요. 다른 사진을 선택하거나 해상도를 낮춰 주세요.',
  ocrDoneToast: (remaining: number) =>
    `분석 완료 · 남은 무료 ${remaining}회 · 음식명을 입력한 뒤 저장해 주세요`,
  nameRequired: '음식명을 입력해 주세요.',
  sectionTemplates: '음식 템플릿',
  templatesHint: '탭해 선택한 뒤 기록 추가하세요. 분량은 저장 후 오늘 목록에서 조절해요.',
  addMeal: '기록 추가',
  saveEdit: '수정 저장',
  deleteMeal: '기록 삭제',
  deleteConfirmTitle: '기록을 삭제할까요?',
  deleteConfirmBody: '삭제한 기록은 목록에서 사라집니다.',
  editBanner: (name: string) => `${name} 수정 중`,
  editSuccess: '수정했어요.',
  deleteSuccess: '삭제했어요.',
  cancelEdit: '수정 취소',
  slotEditHint: '끼니를 바꾼 뒤 아래 수정 저장을 눌러 주세요.',
  saveSuccess: '저장했어요.',
  listTitle: '최근 기록',
  listEmpty: '아직 기록이 없어요.',
  sectionSlot: '끼니',
  sectionSnackWhen: '언제 드셨나요?',
  snackPlacementRequired: '간식 시간을 선택해 주세요.',
  todayTitle: '오늘',
  todayEmpty: '오늘 기록이 없어요.',
  pastTitle: '이전 기록',
  pastLoadingMore: '이전 기록을 불러오는 중…',
  pastBrowseCta: '과거 기록 보기',
  pastBrowseTitle: '과거 기록',
  pastAddMealCta: '이 날짜에 기록 추가',
  pastLogBanner: (dayTitle: string) => `${dayTitle}에 기록 중`,
  pastLogSwitchToday: '오늘로 전환',
  mealDaySummaryTitle: '영양 합계',
  mealDayEmpty: '이 날 기록이 없어요.',
  mealDayLoadError: '식단을 불러오지 못했어요.',
  mealDayRetry: '다시 시도',
  pastEdit: '수정',
  pastDelete: '삭제',
  pastEditModalTitle: '기록 수정',
  pastModalClose: '닫기',
  sectionRecent: '최근 먹은 음식',
  recentHint: '탭하면 아래 입력란에 채워져요.',
  nameSuggestHint: '템플릿·과거 기록에서 선택하면 입력란이 채워져요.',
  nameSuggestEmpty: '일치하는 템플릿·과거 기록이 없어요.',
  nameSuggestLoading: '검색 중…',
  nameSuggestLoadError: '제안을 불러오지 못했어요. 네트워크를 확인해 주세요.',
  nameSuggestNotAvailable: '음식 제안 기능을 사용할 수 없어요. 앱을 최신 버전으로 업데이트해 주세요.',
  pastPortionHint: '목록에서 − / + 로 분량을 바꿀 수 있어요.',
  nameSuggestTemplate: '템플릿',
  manualPortionLabel: '분량 수',
  manualPerServingHint:
    '칼로리·영양소는 1인분(1회 제공량) 기준으로 입력해 주세요. 분량은 저장 후 오늘 목록에서 조절해요.',
  todayPortionHint: '오늘 목록에서 − / + 로 분량을 바꿀 수 있어요.',
  todayEditHint: '항목을 탭하면 위 입력란에서 수정할 수 있어요.',
  portionAdjustError: '분량을 바꾸지 못했어요. 다시 시도해 주세요.',
  protein: '단백질 (g)',
  carb: '탄수화물 (g)',
  fat: '지방 (g)',
  calories: '칼로리 (kcal)',
  switchToManual: '직접 입력',
} as const;
