export const LOG_COPY = {
  title: '기록',
  subtitle: '사진 OCR 또는 아래에서 음식을 골라 기록해요.',
  ocrCamera: '카메라로 촬영',
  ocrAlbum: '앨범에서 선택',
  ocrReviewTitle: 'OCR 결과 확인',
  ocrReviewHint: '값을 확인·수정한 뒤 저장해 주세요.',
  ocrLowConfidence: '신뢰도가 낮아요. 영양 값을 꼭 확인해 주세요.',
  ocrBannerRemaining: '무료 OCR가 1회 남았어요.',
  ocrBannerExhausted: '무료 OCR를 모두 사용했어요.',
  sectionTemplates: '음식 템플릿',
  templatesHint: '탭하면 아래에서 분량을 입력해요.',
  addMeal: '기록 추가',
  saveEdit: '수정 저장',
  deleteMeal: '기록 삭제',
  deleteConfirmTitle: '기록을 삭제할까요?',
  deleteConfirmBody: '삭제한 기록은 목록에서 사라집니다.',
  editBanner: (name: string) => `${name} 수정 중`,
  editSuccess: '수정했어요.',
  deleteSuccess: '삭제했어요.',
  cancelEdit: '수정 취소',
  saveOcr: '식사로 저장',
  saveSuccess: '저장했어요.',
  listTitle: '최근 기록',
  listEmpty: '아직 기록이 없어요.',
  sectionEntry: '입력 방식',
  sectionSlot: '끼니',
  sectionRecent: '최근 먹은 음식',
  recentHint: '탭하면 아래 입력란에 채워져요.',
  protein: '단백질 (g)',
  carb: '탄수화물 (g)',
  fat: '지방 (g)',
  calories: '칼로리 (kcal)',
} as const;
