export const MEAL_SET_COPY = {
  // 진입점 (Log 화면)
  logEntryCta: '세트로 한 번에 등록',

  // 목록 화면
  listTitle: '끼니 세트',
  listSubtitle: '자주 먹는 음식 묶음을 저장해 한 번에 기록해요.',
  listLoadError: '세트를 불러오지 못했어요.',
  retry: '다시 시도',
  empty: '저장된 세트가 없어요.',
  emptyHint: '자주 먹는 끼니를 세트로 만들어 두면 한 번에 기록할 수 있어요.',
  createCta: '새 세트 만들기',
  applyCta: '한 번에 등록',
  editCta: '편집',
  itemCount: (n: number) => `음식 ${n}개`,
  deactivateConfirmTitle: '세트를 삭제할까요?',
  deactivateConfirmBody: '삭제해도 이미 기록한 식사는 그대로 남아요.',
  deactivate: '세트 삭제',
  deactivateSuccess: '세트를 삭제했어요.',
  deactivateError: '세트를 삭제하지 못했어요.',

  // 편집 화면
  editorCreateTitle: '새 세트',
  editorEditTitle: '세트 편집',
  nameLabel: '세트 이름',
  namePlaceholder: '예: 아침 기본 세트',
  nameRequired: '세트 이름을 입력해 주세요.',
  defaultSlotLabel: '기본 끼니',
  snackWhenLabel: '간식은 언제?',
  itemsTitle: '음식 항목',
  itemsHint: '등록된 음식 템플릿을 추가해 세트를 구성해요.',
  itemsEmpty: '항목을 1개 이상 추가해 주세요.',
  addItem: '음식 추가',
  removeItem: '삭제',
  itemUnavailable: '사용 불가',
  itemUnavailableHint: '이 음식은 더 이상 등록할 수 없어요. 교체하거나 삭제해 주세요.',
  save: '저장',
  saveSuccess: '세트를 저장했어요.',
  saveError: '세트를 저장하지 못했어요.',
  itemsMax: (n: number) => `항목은 최대 ${n}개까지 추가할 수 있어요.`,

  // 음식 추가 모달
  addItemTitle: '음식 추가',
  searchPlaceholder: '음식 템플릿 검색',
  searchEmpty: '일치하는 음식 템플릿이 없어요.',
  templatesEmpty: '먼저 기록 화면에서 음식 템플릿을 만들어 주세요.',
  portionLabel: '분량(개수)',
  close: '닫기',
  add: '추가',

  // 한 번에 등록 시트
  applyTitle: '한 번에 등록',
  dateLabel: '날짜',
  prevDay: '하루 전',
  nextDay: '하루 후',
  today: '오늘',
  slotLabel: '끼니',
  futureBlocked: '미래 날짜에는 등록할 수 없어요.',
  previewTitle: (n: number, kcal: number) => `등록될 항목 ${n}개 · 합계 ${kcal} kcal`,
  unavailableBanner: (n: number) => `사용할 수 없는 음식 ${n}개가 포함돼 있어요.`,
  excludeAndApply: '문제 항목 제외 후 등록',
  cancel: '취소',
  excludedBadge: '제외됨',
  applyButton: (n: number) => `${n}건 등록`,
  applyEmpty: '등록할 항목이 없어요.',
  applySuccess: (n: number) => `${n}건을 기록했어요.`,
  applyError: '등록하지 못했어요. 다시 시도해 주세요.',
} as const;
